types: Add missing and undocumented params
Some parameters were undocumented in the JSDoc,
despite existing in the function definition.

As we had labelled some of the earlier params as optional,
this was causing the following error when trying to use
the typescript files:

TypeScript error TS1016:
A required parameter cannot follow an optional parameter